<?php namespace Saiffil\Larafuse\Tables;

class RecurringOrderWithContact extends BaseTable {

	protected $table = 'RecurringOrderWithContact';
	public static $rules = array(
		'RecurringOrderId' => 'required',
		'ContactId' => 'required',
		'ProgramId' => 'required',
		'SubscriptionPlanId' => 'required',
		'ProductId' => 'required',
		'StartDate' => 'required',
		'EndDate' => 'required',
		'LastBillDate' => 'required',
		'NextBillDate' => 'required',
		'PaidThruDate' => 'required',
		'BillingCycle' => 'required',
		'Frequency' => 'required',
		'BillingAmt' => 'required',
		'Status' => 'required',
		'ReasonStopped' => 'required',
		'AutoCharge' => 'required',
		'CC1' => 'required',
		'CC2' => 'required',
		'NumDaysBetweenRetry' => 'required',
		'MaxRetry' => 'required',
		'MerchantAccountId' => 'required',
		'AffiliateId' => 'required',
		'PromoCode' => 'required',
		'LeadAffiliateId' => 'required',
		'Qty' => 'required',
		'City' => 'required',
		'Email' => 'required',
		'EmailAddress2' => 'required',
		'EmailAddress3' => 'required',
		'FirstName' => 'required',
		'HTMLSignature' => 'required',
		'LastName' => 'required',
		'MiddleName' => 'required',
		'Nickname' => 'required',
		'Phone1' => 'required',
		'Phone1Ext' => 'required',
		'Phone1Type' => 'required',
		'Phone2' => 'required',
		'Phone2Ext' => 'required',
		'Phone2Type' => 'required',
		'PostalCode' => 'required',
		'Signature' => 'required',
		'SpouseName' => 'required',
		'State' => 'required',
		'Country' => 'required',
		'StreetAddress1' => 'required',
		'StreetAddress2' => 'required',
		'Suffix' => 'required',
		'Title' => 'required',
		'ZipFour1' => 'required'
	);
}
